name: "Common Setup"
description: "Common setup for building the project"

runs:
  using: "composite"
  steps:
  - shell: bash
    run: echo ${{ hashFiles('requirements.txt') }}
  - uses: actions/cache@v3
    with:
      path: output.txt
      key: ${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      restore-keys: ${{ runner.os }}-
