name: "Common Setup"
description: "Common setup for building the project"

runs:
  using: "composite"
  steps:
  - shell: bash
    run: git fetch -q --prune --unshallow
  - shell: bash
    run: echo ${{ hashFiles('**/requirements.txt', 'req1.txt') }}
  - uses: actions/cache@v3
    with:
      path: output.txt
      key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt', 'req1.txt') }}
      restore-keys: ${{ runner.os }}-
