name: Main

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ hashFiles('requirements.txt') }}
    - uses: ./.github/actions/common-setup
    - run: echo "something" > output.txt
